apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  namespace: micro-app
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: consumer-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-app
  namespace: micro-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-app
  template:
    metadata:
      labels:
        app: consumer-app
    spec:
      containers:
      - name: consumer-app
        image: microservices-app-consumer_service
        imagePullPolicy: Never
        env:
          - name: RABBIT_HOST
            value: "rabbitmq"
          - name: DB_HOST
            value: "mysql-db"
          - name: DB_PASSWORD
            value: "password"
        ports:
          - containerPort: 8081